version: '4.0'

actions:
  generate_full_study_cohort:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_full_study_cohort.py --output output/full_study_cohort.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/full_study_cohort.csv.gz

  generate_dataset_for_census_2021:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_census_cohorts.py 
      --output output/census_2021_study_cohort.csv.gz
      --
      --census-date "2021-03-21"
    outputs:
      highly_sensitive:
        dataset: output/census_2021_study_cohort.csv.gz

  generate_dataset_for_census_2011:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_census_cohorts.py 
      --output output/census_2011_study_cohort.csv.gz
      --
      --census-date "2011-03-27"
    outputs:
      highly_sensitive:
        dataset: output/census_2011_study_cohort.csv.gz

  generate_km_time_to_first_migration_code_cohort:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_km_time_to_first_migration_code.py --output output/km_time_to_first_migration_code_cohort.arrow
    outputs:
      highly_sensitive:
        dataset: output/km_time_to_first_migration_code_cohort.arrow

  km_time_to_first_migration_code:
    run: kaplan-meier-function:v0.0.14
      --df_input=output/km_time_to_first_migration_code_cohort.arrow
      --dir_output=output/km_estimates/
      --exposure=has_a_migration_code
      --origin_date=baseline_date
      --event_date=processed_first_migration_code_date
      --censor_date=censor_date
      --min_count=6
      --plot=TRUE
    needs:
    - generate_km_time_to_first_migration_code_cohort 
    outputs:
      highly_sensitive:
        estimates: output/km_estimates/estimates.arrow
        contrasts: output/km_estimates/contrasts.arrow
        plots: output/km_estimates/plot.png

  generate_demographics_table_for_full_study_cohort:
    run: r:latest analysis/demographics_full_study_cohort.r --output output/tables/demographics.csv
    needs: 
    - generate_full_study_cohort
    outputs:
      moderately_sensitive:
        csv: output/tables/demographics.csv

  generate_annual_migrant_counts_broken_down:
    run: ehrql:v1 generate-measures analysis/generate_annual_migrant_counts.py --output output/tables/annual_migrant_counts.csv
    outputs:
      moderately_sensitive:
        csv: output/tables/annual_migrant_counts.csv

 
